### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by H0neyCake** [oberbichler/earcut.net#3]
Please, add some usage examples in the readme. It will be much easier than digging in your tests.

**Comment by oberbichler** [comment]
It is a direct port of [earcut.js by Mapbox](https://github.com/mapbox/earcut). There you will also find some examples.

**Comment by H0neyCake** [comment]
Different entry point.

**Comment by H0neyCake** [comment]
Also formatting system very different. 
How to use this features? 
```
// triangulating a polygon with a hole
earcut([0,0, 100,0, 100,100, 0,100,  20,20, 80,20, 80,80, 20,80], [4]);
// [3,0,4, 5,4,0, 3,4,7, 5,0,1, 2,3,7, 6,5,1, 2,7,6, 6,1,2]

// triangulating a polygon with 3d coords
earcut([10,0,1, 0,50,2, 60,60,3, 70,10,4], null, 3);
// [1,0,3, 3,2,1]
```

**Comment by oberbichler** [comment]
First example should work in exact the same way.
Second example: no support for the dimension parameter yet.

**Comment by oberbichler** [comment]
I have just added a small example to the `README`. Take a look at it.

**Comment by H0neyCake** [comment]
Thanks.
